### ISSUE TITLE
Touch Issue on ipad and mobiles : skdslider

### ISSUE THREAD

**Issue by jayeshnetstager** [samirkumardas/skdslider#4]
Hi ,
On Ipad and Mobiles; While touch and swipe the page to top on slider  there is only change in slider images. The page is not scrolling.

Anyone have the answer?

**Comment by William-Michael-Russell** [comment]
Im looking to figure this out too.

**Comment by William-Michael-Russell** [comment]
ok after about 40 minutes of debugging... I've nailed it down to this:

javascript: skdslider.min.js

```
e.skdslider.enableTouch = function (t, n, r) {
        function a(e) {
            i = e.touches[0].pageX;
            s = e.touches[0].pageY;

            t[0].addEventListener("touchmove", f, false);
            t[0].addEventListener("touchend", l, false)
        }

        function f(e) {
            var isiPad = navigator.userAgent.match(/iPad/i) != null;
            if (!isiPad) {
                e.preventDefault();
            }
            var t = e.touches[0].pageX;
            var n = e.touches[0].pageY;
            o = i - t;
            u = s - n
        }
```

t[0].addEventListener("touchmove", f, false); is preventing the scroll VIA e.preventDefault();

I will need to test other devices, but this fixed my iPad issue. 

Assumption...
I believe they disable "touchmove" so that users can't slide the images left and right.
I've added that hack above for iPad since my site has automatic scrolling enabled, and also the left/right arrows to click on.

Risks:
If you don't have automatic slider enabled, or the arrows, your users can slide left and right.

Actual fix:
I believe "touchmove" should only be disabled with horizontal scrolling, not vertical.

Please let me know if you find a better fix

At least we know the root cause now :)

**Comment by jayeshnetstager** [comment]
Hi Dear Friend williamrussellajb ,

Sorry for the late comment.

Thank you for your Help, This was very useful, Your Code is better for ipad, If We change ipad to iphone It will perfect to Iphones. 

Let me know, It is possible to add the code for both devices?

**Comment by williamrussell-grindr** [comment]
@jayeshnetstager 
Yes, please add it. I tested across multiple devices with it. iPhones still work, and this fixes iPads.

My hobby website is using it and I haven't had any issues. 

Let me know if you need anything, 
Thanks!

**Comment by William-Michael-Russell** [comment]
@jayeshnetstager 
Yes, please add it. I tested across multiple devices with it. iPhones still work, and this fixes iPads.

My hobby website is using it and I haven't had any issues.

Let me know if you need anything, 
Thanks!

**Comment by William-Michael-Russell** [comment]
@samirkumardas is this worth making a commit for?

**Comment by jayeshnetstager** [comment]
@williamrussellajb ,

I used the script you given above, But It is working only in Ipad, and renamed ipad to iphone it working only in iphone. Can you show me the script working in both devices?

**Comment by pabloacastillo** [comment]
Hi there, got same problem solved the issue like this:



	function onTouchMove(e) {
		var x = e.touches[0].pageX;
		var y = e.touches[0].pageY;
		dx = startX - x;
		dy = startY - y;

		if(Math.abs(dy)>Math.abs(dx)){
			console.log('VERTICAL CONGA!');
		} else {
			e.preventDefault();
			console.log('HORIZONTAL CONGA');
		}
	}


Ugly but it works (in Chrome, not tested in other browsers)
